# Generated by Django 5.1.6 on 2026-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_vehicle_agent_vehicle_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='staff.location'),
        ),
    ]
