# Generated by Django 5.1.6 on 2026-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_vehicle_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleunavailability',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleunavailability',
            name='reason',
            field=models.CharField(choices=[('external_booking', 'External Booking (e.g. Airbnb/Manual)'), ('maintenance', 'Maintenance / Service'), ('personal', 'Personal Use'), ('other', 'Other')], default='external_booking', max_length=50),
        ),
    ]
