# Generated by Django 5.1.6 on 2026-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_vehicleunavailability_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleunavailability',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
